#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

info() { echo -e "${BLUE}▶${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }

ASSETS_DIR="assets"
OUTPUT_FILE="src/generated/assets.ts"

info "Generating asset bundle..."

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Start the file
echo "// Auto-generated by scripts/generate-assets.sh - DO NOT EDIT" >"$OUTPUT_FILE"
echo "" >>"$OUTPUT_FILE"

# Process each PDF
for pdf in "$ASSETS_DIR"/*.pdf; do
    [[ -e "$pdf" ]] || continue

    filename=$(basename "$pdf")
    varname=$(echo "${filename%.*}" | tr '[:lower:]-' '[:upper:]_')

    base64_data=$(base64 -w 0 "$pdf" 2>/dev/null || base64 -i "$pdf" | tr -d '\n')

    echo "export const ${varname}_PDF = \"data:application/pdf;base64,${base64_data}\";" >>"$OUTPUT_FILE"
    echo "" >>"$OUTPUT_FILE"

    info "  Bundled: $filename"
done

# Process card backs
echo "export const CARD_BACKS: { id: string; name: string; data: string }[] = [" >>"$OUTPUT_FILE"

for img in "$ASSETS_DIR"/card-backs/*.{jpg,png}; do
    [[ -e "$img" ]] || continue

    filename=$(basename "$img")
    name="${filename%.*}"
    ext="${filename##*.}"

    # Determine mime type
    if [[ "$ext" == "png" ]]; then
        mime="image/png"
    else
        mime="image/jpeg"
    fi

    base64_data=$(base64 -w 0 "$img" 2>/dev/null || base64 -i "$img" | tr -d '\n')

    echo "  { id: \"default-$name\", name: \"$name\", data: \"data:$mime;base64,$base64_data\" }," >>"$OUTPUT_FILE"

    info "  Bundled: card-backs/$filename"
done

echo "];" >>"$OUTPUT_FILE"
echo "" >>"$OUTPUT_FILE"

success "Generated $OUTPUT_FILE"
