#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

info() { echo -e "${BLUE}▶${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }

ASSETS_DIR="assets"
OUTPUT_FILE="src/generated/assets.ts"

info "Generating asset bundle..."

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Start the file
echo "// Auto-generated by scripts/generate-assets.sh - DO NOT EDIT" >"$OUTPUT_FILE"
echo "" >>"$OUTPUT_FILE"

# Process each PDF
for pdf in "$ASSETS_DIR"/*.pdf; do
    [[ -e "$pdf" ]] || continue

    filename=$(basename "$pdf")
    varname=$(echo "${filename%.*}" | tr '[:lower:]-' '[:upper:]_')

    base64_data=$(base64 -w 0 "$pdf" 2>/dev/null || base64 -i "$pdf" | tr -d '\n')

    echo "export const ${varname}_PDF = \"data:application/pdf;base64,${base64_data}\";" >>"$OUTPUT_FILE"
    echo "" >>"$OUTPUT_FILE"

    info "  Bundled: $filename"
done

success "Generated $OUTPUT_FILE"
